// examples/angular/my-app/src/app/student/student.component.ts
import { Component, OnInit } from '@angular/core';

import { StudentService } from '../service/student.service';
import { Student, IStudent } from '../model/student';



@Component({

  selector: 'app-student',

  templateUrl: './student.component.html',

  styleUrls: ['./student.component.css'],

  providers: [StudentService]

})
export class StudentComponent implements OnInit {

  private service: StudentService;
  students: Array<IStudent> = [];
  newStudent: IStudent = new Student();
  oldStudent: IStudent = new Student();

  constructor(service: StudentService) {
    this.service = service;
  }


  ngOnInit() {
    this.getStudents();
  }

  async getStudents() {
    try {
      this.students = await this.service.getStudents()
    }
    catch (error) {
      console.error(error);
      alert(error.message);
    }
  }

  async addStudent() {
    try {
      const addedStudents = await this.service.addStudent(this.newStudent) as IStudent[];
      if (addedStudents.length > 0) {
        this.students.push(addedStudents[0]);
        this.clearNewStudent();
        alert('Successfully added');
      }
    }
    catch (error) {
      console.error(error);
      alert(error.message);
    }
  }

  clearNewStudent() {
    this.newStudent = new Student();
  }

  async deleteStudent(studentId) {
    try {
      const noOfrowsDeleted = await this.service.deleteStudent(studentId);
      if (noOfrowsDeleted > 0) {
        const index = this.students.findIndex(student => student.id === studentId);
        this.students.splice(index, 1);
        alert('Successfully deleted');
      }
    }
    catch (error) {
      console.error(error);
      alert(error.message);
    }

  }

  clearOldStudent() {
    this.oldStudent = new Student();
  }

  async getStudent(studentId) {
    try {
      const students = await this.service.getStudent(studentId);
      if (students.length > 0) {
        this.oldStudent = students[0];
      }
    }
    catch (error) {
      console.error(error);
      alert(error.message);
    }

  }

  async updateStudent() {
    const updatedValue: IStudent = {
      name: this.oldStudent.name,
      gender: this.oldStudent.gender,
      country: this.oldStudent.country,
      city: this.oldStudent.city
    };
    try {
      const noOfrowsUpdated = await this.service.updateStudent(this.oldStudent.id, updatedValue);
      if (noOfrowsUpdated > 0) {
        const index = this.students.findIndex(student => student.id === this.oldStudent.id);
        this.students[index] = this.oldStudent;
        this.clearOldStudent();
        alert('Successfully updated');
      }
    }
    catch (error) {
      console.error(error);
      alert(error.message);
    }
  }

}

<table>
  <tr>
    <th>Student Name</th>
    <th>gender</th>
    <th>country</th>
    <th>city</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td>
      <input type="text" [(ngModel)]="newStudent.name" />
    </td>
    <td>
      <select [(ngModel)]="newStudent.gender">
        <option value="m">Male</option>
        <option value="f">FeMale</option>
      </select>
    </td>
    <td>
      <input type="text" [(ngModel)]="newStudent.country" />
    </td>
    <td>
      <input type="text" [(ngModel)]="newStudent.city" />
    </td>
    <td>
      <button (click)="addStudent()">Add</button>
    </td>
    <td>
      <button (click)="clearNewStudent()">Cancel</button>
    </td>
  </tr>
  <tr *ngFor="let student of students" [attr.data-id]="student.id">
    <td>
      <input type="text" *ngIf="student.editing" [(ngModel)]="oldStudent.name" />
      <span *ngIf="!student.editing">
        {{student.name}}
      </span>
    </td>
    <td>
      <select *ngIf="student.editing" [(ngModel)]="oldStudent.gender">
        <option value="m">Male</option>
        <option value="f">FeMale</option>
      </select>
      <span *ngIf="!student.editing">{{student.gender=='m'?'Male':'Female'}}</span>
    </td>
    <td>
      <input type="text" *ngIf="student.editing" [(ngModel)]="oldStudent.country" />
      <span *ngIf="!student.editing">{{student.country}}</span>
    </td>
    <td>
      <input type="text" *ngIf="student.editing" [(ngModel)]="oldStudent.city" />
      <span *ngIf="!student.editing">{{student.city}}</span>
    </td>
    <td>
      <button *ngIf="student.editing" (click)="updateStudent();student.editing=false">Update</button>
      <button *ngIf="!student.editing" (click)="student.editing=true;getStudent(student.id);">Edit</button>
    </td>
    <td>
      <button *ngIf="student.editing" (click)="student.editing=false">Cancel</button>
      <button *ngIf="!student.editing" (click)="deleteStudent(student.id)">Delete</button>
    </td>
  </tr>
</table>

// examples/vue-crud/src/components/Student.vue
<template>
  <table>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Country</th>
      <th>City</th>
    </tr>
    <tr>
      <td>
        <input type="text" v-model="newStudent.name">
      </td>
      <td>
        <input type="text" v-model="newStudent.gender">
      </td>
      <td>
        <input type="text" v-model="newStudent.country">
      </td>
      <td>
        <input type="text" v-model="newStudent.city">
      </td>
      <td>
        <button @click="add">Add</button>
      </td>
      <td>
        <button @click="clear">Clear</button>
      </td>
    </tr>
    <tr v-for="student in students" :key="student.id">
      <template v-if="editStudent!=null && editStudent.id==student.id">
        <td>
          <input type="text" v-model="editStudent.name">
        </td>
        <td>
          <input type="text" v-model="editStudent.gender">
        </td>
        <td>
          <input type="text" v-model="editStudent.country">
        </td>
        <td>
          <input type="text" v-model="editStudent.city">
        </td>
        <td>
          <button @click="update(editStudent.id)">Update</button>
        </td>
        <td>
          <button @click="cancelUpdate">Cancel</button>
        </td>
      </template>
      <template v-else>
        <td>{{student.name}}</td>
        <td>{{student.gender}}</td>
        <td>{{student.country}}</td>
        <td>{{student.city}}</td>
        <td>
          <button @click="edit(student.id)">Edit</button>
        </td>
        <td>
          <button @click="remove(student.id)">Delete</button>
        </td>
      </template>
      
    </tr>
  </table>
</template>
<script>
import { StudentService } from "../service/student_service";
export default {
  name: "Student",
  data: function() {
    return {
      students: [],
      newStudent: null,
      editStudent: null
    };
  },
  beforeMount: function() {
    this.clear();
  },
  mounted: function() {
    this.refreshStudent();
  },
  methods: {
    refreshStudent: async function() {
      this.students = await new StudentService().getStudents();
    },
    add: async function() {
      try {
        const studentsAdded = await new StudentService().addStudent(
          this.newStudent
        );
        this.students.push(studentsAdded[0]);
        this.clear();
      } catch (ex) {
        // handle exception
      }
    },
    clear: function() {
      this.newStudent = {
        name: "",
        gender: "",
        country: "",
        city: ""
      };
    },
    edit: function(id) {
      var student = this.students.find(qry => qry.id === id);
      this.editStudent = {
        id: student.id,
        name: student.name,
        gender: student.gender,
        country: student.country,
        city: student.city
      };
    },
    remove: async function(id) {
      const service = new StudentService();
      const noOfStudentRemoved = await service.removeStudent(id);
      this.refreshStudent();
    },
    update: async function(id) {
      const service = new StudentService();
      await service.updateStudentById(id, {
        name: this.editStudent.name,
        gender: this.editStudent.gender,
        country: this.editStudent.country,
        city: this.editStudent.city
      });
      this.editStudent = null;
      this.refreshStudent();
    },
    cancelUpdate: function() {
      this.editStudent = null;
    }
  }
};
</script>
